name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: |
          cpanm -n --installdeps .
      - name: Run tests
        run: prove -l -v t/*.t
